import { APP_VERSION } from "../lib/app-version";
import type {
  AppSetting,
  BagType,
  ContextOption,
  ContextOptionType,
  GadgetBundle,
  GadgetBundleItem,
  Template,
  TemplateConditionRule,
  TemplateItem,
  UsefulExtra,
  TripType,
} from "./types";

export const SEED_VERSION = "0.11.0";

export const seededTravellers = [];

export const seededContextOptions: ContextOption[] = [
  ...contextOptions("climate", [
    "Hot",
    "Warm",
    "Mild",
    "Cool",
    "Cold",
    "Snow / Winter",
    "Wet / Rainy",
    "Mixed / Variable",
    "Indoor-heavy",
    "Sun-exposed",
  ]),
  ...contextOptions("accommodation", [
    "Hotel",
    "Resort",
    "Cruise cabin",
    "Villa",
    "Apartment",
    "Cottage",
    "Lodge",
    "Caravan / Holiday park",
    "Self-catering",
    "Friends or family stay",
    "Multi-centre / mixed accommodation",
  ]),
  ...contextOptions("transport", [
    "Flight",
    "Cruise",
    "Car",
    "Train",
    "Taxi / transfer",
    "Hire car",
    "Walking-heavy",
    "Coach / shuttle",
    "Ferry",
    "Public transport",
  ]),
  ...contextOptions("activity", [
    "Pool",
    "Beach",
    "Theme park",
    "Cruise formal night",
    "Cruise embarkation",
    "City walking",
    "Excursion",
    "Hiking / countryside",
    "Restaurant / evening dining",
    "Photography",
    "Kids' clubs",
    "Long travel day",
    "Dog-friendly stay",
    "Self-catering meals",
    "Rainy day",
    "Cold weather activities",
    "Special occasion",
    "Sport / active play",
    "Water park",
    "Airport overnight / stopover",
  ]),
];

export const seededCategories = [
  "clothing",
  "toiletries",
  "documents",
  "electronics",
  "health",
  "comfort",
  "entertainment",
  "travel-day",
  "cruise-extras",
  "misc",
  "pet",
  "weather",
  "laundry",
];

export const seededBagTypes: BagType[] = [
  "suitcase",
  "cabin-bag",
  "backpack",
  "handbag",
  "pouch",
  "day-bag",
  "camera-bag",
  "car-storage",
  "worn",
  "buy-later",
];

export const seededTemplates: Template[] = [
  template("cruise", "Cruise", ["cruise", "ex-uk-cruise"], [
    "formal-night",
    "pool",
    "excursion",
  ]),
  template("fly-cruise", "Fly-cruise", ["fly-cruise"], [
    "flight",
    "formal-night",
    "pool",
  ]),
  template("beach-holiday", "Beach holiday", ["beach-holiday"], [
    "pool",
    "beach",
  ]),
  template("theme-park", "Disney or theme park", ["theme-park"], [
    "theme-park",
    "walking",
  ]),
  template("staycation", "Staycation", ["staycation"], ["car", "self-catering"]),
  template("cold-weather", "Cold weather", ["cold-weather"], ["cold", "walking"]),
  template("city-break", "City break", ["city-break"], ["walking", "sightseeing"]),
  template("weekend-break", "Weekend break", ["short-break"], ["weekend"]),
  template("dog-friendly-uk", "Dog-friendly UK stay", ["staycation", "short-break"], [
    "dog-friendly",
    "car",
  ]),
];

export const seededTemplateItems: TemplateItem[] = [
  templateItem("cruise:passport", "cruise", "Passports", "shared", "documents", "essential"),
  templateItem("cruise:cruise-docs", "cruise", "Cruise boarding documents", "shared", "documents", "essential"),
  templateItem("cruise:lanyards", "cruise", "Cruise card lanyards", "shared", "cruise-extras", "useful"),
  templateItem("cruise:magnetic-hooks", "cruise", "Magnetic cabin hooks", "shared", "cruise-extras", "useful"),
  templateItem("cruise:formal-outfit", "cruise", "Formal night outfit", "selected-adult", "clothing", "important", [
    includesRule("activityContextIds", "formal-night"),
  ]),
  templateItem("cruise:swimwear", "cruise", "Swimwear", "selected-adult", "clothing", "important", [
    includesRule("activityContextIds", "pool"),
  ]),
  templateItem("fly-cruise:flight-docs", "fly-cruise", "Flight booking references", "shared", "documents", "essential"),
  templateItem("fly-cruise:plane-comfort", "fly-cruise", "Plane comfort pouch", "shared", "comfort", "useful"),
  templateItem("fly-cruise:hand-luggage-clothes", "fly-cruise", "Hand luggage spare clothes", "selected-adult", "clothing", "important"),
  templateItem("beach:sunscreen", "beach-holiday", "Sunscreen", "shared", "health", "essential"),
  templateItem("beach:beach-bag", "beach-holiday", "Beach bag", "shared", "travel-day", "important"),
  templateItem("beach:swimwear", "beach-holiday", "Swimwear", "selected-adult", "clothing", "important"),
  templateItem("theme-park:ponchos", "theme-park", "Lightweight ponchos", "shared", "weather", "useful"),
  templateItem("theme-park:power-bank", "theme-park", "Power bank", "shared", "electronics", "important"),
  templateItem("theme-park:kids-entertainment", "theme-park", "Queue entertainment", "selected-child", "entertainment", "useful"),
  templateItem("staycation:food-bags", "staycation", "Reusable food bags", "shared", "misc", "useful"),
  templateItem("staycation:washing-tabs", "staycation", "Laundry tablets", "shared", "laundry", "useful"),
  templateItem("cold:thermal-layers", "cold-weather", "Thermal layers", "selected-adult", "clothing", "important"),
  templateItem("cold:gloves", "cold-weather", "Gloves", "selected-adult", "clothing", "important"),
  templateItem("city:day-bag", "city-break", "Small day bag", "shared", "travel-day", "important"),
  templateItem("city:walking-shoes", "city-break", "Comfortable walking shoes", "selected-adult", "clothing", "essential"),
  templateItem("weekend:overnight-toiletries", "weekend-break", "Overnight toiletries", "selected-adult", "toiletries", "important"),
  templateItem("weekend:chargers", "weekend-break", "Phone chargers", "shared", "electronics", "essential"),
  templateItem("dog:lead", "dog-friendly-uk", "Dog lead", "dog", "pet", "essential"),
  templateItem("dog:food", "dog-friendly-uk", "Dog food", "dog", "pet", "essential"),
  templateItem("dog:towels", "dog-friendly-uk", "Dog towels", "dog", "pet", "important"),
  templateItem("cruise:travel-adapter", "cruise", "Travel adapter", "shared", "electronics", "important"),
  templateItem("cruise:boarding-bag", "cruise", "Embarkation day bag", "shared", "travel-day", "important"),
  templateItem("cruise:medicines", "cruise", "Regular medicines", "each-traveller", "health", "essential"),
  templateItem("cruise:excursion-bag", "cruise", "Excursion day bag", "shared", "travel-day", "important", [includesRule("activityContextIds", "excursion")]),
  templateItem("cruise:sun-hat", "cruise", "Sun hat", "each-traveller", "clothing", "important"),
  templateItem("cruise:evening-shoes", "cruise", "Evening shoes", "selected-adult", "clothing", "useful", [includesRule("activityContextIds", "formal-night")]),
  templateItem("fly-cruise:passports", "fly-cruise", "Passports", "shared", "documents", "essential"),
  templateItem("fly-cruise:cruise-docs", "fly-cruise", "Cruise boarding documents", "shared", "documents", "essential"),
  templateItem("fly-cruise:travel-adapter", "fly-cruise", "Travel adapter", "shared", "electronics", "important"),
  templateItem("fly-cruise:medicines", "fly-cruise", "Regular medicines", "each-traveller", "health", "essential"),
  templateItem("fly-cruise:swimwear", "fly-cruise", "Swimwear", "each-traveller", "clothing", "important"),
  templateItem("fly-cruise:lanyards", "fly-cruise", "Cruise card lanyards", "shared", "cruise-extras", "useful"),
  templateItem("beach:passports", "beach-holiday", "Passports", "shared", "documents", "essential"),
  templateItem("beach:sun-hats", "beach-holiday", "Sun hats", "shared", "clothing", "important"),
  templateItem("beach:evening-outfit", "beach-holiday", "Evening outfit", "selected-adult", "clothing", "important"),
  templateItem("beach:pool-shoes", "beach-holiday", "Pool or beach shoes", "each-traveller", "clothing", "useful"),
  templateItem("beach:travel-day-snacks", "beach-holiday", "Travel day snacks", "shared", "travel-day", "useful"),
  templateItem("beach:chargers", "beach-holiday", "Phone chargers", "shared", "electronics", "essential"),
  templateItem("theme-park:walking-shoes", "theme-park", "Comfortable walking shoes", "each-traveller", "clothing", "essential"),
  templateItem("theme-park:water-bottle", "theme-park", "Refillable water bottle", "each-traveller", "travel-day", "important"),
  templateItem("theme-park:sun-hats", "theme-park", "Sun hats", "shared", "clothing", "important"),
  templateItem("theme-park:snacks", "theme-park", "Day bag snacks", "shared", "travel-day", "useful"),
  templateItem("theme-park:blister-plasters", "theme-park", "Blister plasters", "shared", "health", "important"),
  templateItem("theme-park:short-cable", "theme-park", "Short phone charging cable", "shared", "electronics", "important"),
  templateItem("staycation:chargers", "staycation", "Phone chargers", "shared", "electronics", "essential"),
  templateItem("staycation:weather-layer", "staycation", "Weatherproof outer layer", "each-traveller", "weather", "important"),
  templateItem("staycation:medicines", "staycation", "Regular medicines", "each-traveller", "health", "essential"),
  templateItem("staycation:shopping-bags", "staycation", "Reusable shopping bags", "shared", "misc", "useful"),
  templateItem("cold:warm-coat", "cold-weather", "Warm coat", "each-traveller", "clothing", "essential"),
  templateItem("cold:warm-hat", "cold-weather", "Warm hat", "each-traveller", "clothing", "important"),
  templateItem("cold:scarf", "cold-weather", "Scarf", "each-traveller", "clothing", "important"),
  templateItem("cold:waterproof-boots", "cold-weather", "Waterproof boots", "each-traveller", "clothing", "important"),
  templateItem("cold:spare-camera-battery", "cold-weather", "Spare camera battery", "shared", "electronics", "useful", [includesRule("activityContextIds", "photography")]),
  templateItem("city:documents", "city-break", "Travel documents", "shared", "documents", "essential"),
  templateItem("city:phone-charger", "city-break", "Phone charger", "shared", "electronics", "essential"),
  templateItem("city:weather-layer", "city-break", "Light weatherproof layer", "each-traveller", "weather", "important"),
  templateItem("city:evening-outfit", "city-break", "Restaurant or evening outfit", "selected-adult", "clothing", "useful"),
  templateItem("city:water-bottle", "city-break", "Refillable water bottle", "shared", "travel-day", "useful"),
  templateItem("weekend:underwear", "weekend-break", "Underwear", "each-traveller", "clothing", "essential"),
  templateItem("weekend:change-of-clothes", "weekend-break", "Change of clothes", "each-traveller", "clothing", "essential"),
  templateItem("weekend:medicines", "weekend-break", "Regular medicines", "each-traveller", "health", "essential"),
  templateItem("dog:water-bowl", "dog-friendly-uk", "Dog water bowl", "dog", "pet", "important"),
  templateItem("dog:poo-bags", "dog-friendly-uk", "Dog poo bags", "dog", "pet", "essential"),
  templateItem("dog:bed", "dog-friendly-uk", "Dog bed or blanket", "dog", "pet", "important"),
  templateItem("dog:medicines", "dog-friendly-uk", "Dog medicines", "dog", "pet", "essential"),
  templateItem("dog:walking-gear", "dog-friendly-uk", "Dog walking gear", "dog", "pet", "important"),
];

export const seededUsefulExtras: UsefulExtra[] = [
  usefulExtra("plane-comfort:eye-mask", "Eye mask", "comfort", ["fly-cruise", "city-break"], ["flight"]),
  usefulExtra("plane-comfort:empty-water-bottle", "Empty water bottle", "travel-day", ["fly-cruise", "city-break"], ["flight"], true),
  usefulExtra("cruise:cabin-night-light", "Cabin night light", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise"]),
  usefulExtra("cruise:over-door-organiser", "Over-door organiser", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise"]),
  usefulExtra("theme-park:cooling-towel", "Cooling towel", "comfort", ["theme-park", "beach-holiday"], ["theme-park", "hot"]),
  usefulExtra("hotel:travel-washing-line", "Travel washing line", "laundry", ["beach-holiday", "staycation"], ["hotel", "pool"]),
  usefulExtra("pool:waterproof-phone-pouch", "Waterproof phone pouch", "electronics", ["beach-holiday", "cruise", "fly-cruise"], ["pool", "beach"]),
  usefulExtra("photo:spare-memory-card", "Spare memory card", "electronics", ["cruise", "city-break", "theme-park"], ["photography"]),
  usefulExtra("gadgets:cable-ties", "Cable ties", "electronics", ["cruise", "fly-cruise", "staycation"], ["gadgets"]),
  usefulExtra("kids:headphones", "Kids headphones", "entertainment", ["fly-cruise", "theme-park", "staycation"], ["kids"]),
  usefulExtra("health:plasters", "Plasters", "health", ["cruise", "fly-cruise", "theme-park", "city-break"], ["walking"], true),
  usefulExtra("documents:insurance", "Travel insurance details", "documents", ["cruise", "fly-cruise", "city-break"], ["admin"], true),
  usefulExtra("weather:compact-umbrella", "Compact umbrella", "weather", ["city-break", "staycation", "short-break"], ["weather"]),
  usefulExtra("car:snack-box", "Car snack box", "travel-day", ["staycation", "short-break"], ["car"]),
  usefulExtra("dog:poo-bags", "Poo bags", "pet", ["staycation", "short-break"], ["dog-friendly"], true),
  usefulExtra("plane-comfort:phone-stand", "Plane phone stand", "comfort", ["fly-cruise", "city-break", "beach-holiday"], ["flight"]),
  usefulExtra("plane-comfort:bluetooth-adapter", "Bluetooth audio adapter", "electronics", ["fly-cruise", "city-break", "beach-holiday"], ["flight"]),
  usefulExtra("plane-comfort:headphone-splitter", "Headphone splitter", "electronics", ["fly-cruise", "theme-park", "beach-holiday"], ["flight", "kids"]),
  usefulExtra("gadgets:compact-power-bank", "Compact power bank", "electronics", ["theme-park", "city-break", "cruise", "fly-cruise"], ["long-travel-day", "theme-park"]),
  usefulExtra("gadgets:usb-c-multi-cable", "USB-C multi-cable", "electronics", ["cruise", "fly-cruise", "city-break", "staycation"], ["gadgets"]),
  usefulExtra("gadgets:plug-cube", "USB plug cube", "electronics", ["cruise", "fly-cruise", "staycation"], ["gadgets"]),
  usefulExtra("gadgets:travel-adapter", "Travel adapter", "electronics", ["fly-cruise", "city-break", "beach-holiday", "cruise"], ["flight", "cruise"]),
  usefulExtra("cruise:magnetic-hooks", "Magnetic cruise hooks", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise"]),
  usefulExtra("cruise:lanyards", "Cruise card lanyards", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise"]),
  usefulExtra("cruise:card-holder", "Cruise card holder", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise"]),
  usefulExtra("cruise:luggage-tag-holders", "Cruise luggage tag holders", "cruise-extras", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise-embarkation"]),
  usefulExtra("cruise:towel-clips", "Towel clips", "cruise-extras", ["cruise", "fly-cruise", "beach-holiday"], ["pool", "beach"]),
  usefulExtra("organisation:wet-bag", "Wet bag", "misc", ["beach-holiday", "cruise", "theme-park"], ["pool", "beach", "water-park"]),
  usefulExtra("organisation:ziplock-bags", "Ziplock bags", "misc", ["cruise", "fly-cruise", "beach-holiday", "staycation"], ["travel-day"]),
  usefulExtra("organisation:packing-cubes", "Packing cubes", "misc", ["cruise", "fly-cruise", "beach-holiday", "city-break"], ["travel-day"]),
  usefulExtra("laundry:laundry-bag", "Laundry bag", "laundry", ["cruise", "fly-cruise", "beach-holiday", "staycation"], ["hotel", "self-catering"]),
  usefulExtra("laundry:stain-remover", "Stain remover pen", "laundry", ["theme-park", "cruise", "beach-holiday"], ["kids", "restaurant-evening-dining"]),
  usefulExtra("pool:collapsible-bottle", "Collapsible water bottle", "travel-day", ["theme-park", "city-break", "cruise"], ["walking", "theme-park"]),
  usefulExtra("comfort:portable-fan", "Portable fan", "comfort", ["theme-park", "beach-holiday", "cruise"], ["hot", "sun-exposed"]),
  usefulExtra("weather:ponchos", "Lightweight ponchos", "weather", ["theme-park", "city-break", "staycation"], ["wet-rainy", "theme-park"]),
  usefulExtra("pool:spare-sunglasses", "Spare sunglasses", "clothing", ["beach-holiday", "cruise", "theme-park"], ["sun-exposed"]),
  usefulExtra("pool:swim-goggles", "Swim goggles", "misc", ["beach-holiday", "cruise", "theme-park"], ["pool", "water-park"]),
  usefulExtra("health:blister-plasters", "Blister plasters", "health", ["city-break", "theme-park", "cruise"], ["walking-heavy", "city-walking"], true),
  usefulExtra("health:first-aid-kit", "Mini first-aid kit", "health", ["staycation", "theme-park", "cruise", "beach-holiday"], ["travel-day"]),
  usefulExtra("health:antibac-wipes", "Anti-bac wipes", "health", ["fly-cruise", "theme-park", "staycation"], ["long-travel-day"]),
  usefulExtra("health:travel-sickness", "Travel sickness remedy", "health", ["cruise", "fly-cruise", "staycation"], ["cruise", "car"]),
  usefulExtra("health:child-medicine", "Child medicine reminder", "health", ["cruise", "fly-cruise", "beach-holiday", "theme-park"], ["kids"]),
  usefulExtra("health:thermometer", "Travel thermometer", "health", ["cruise", "fly-cruise", "beach-holiday", "staycation"], ["kids"]),
  usefulExtra("kids:snacks-pouch", "Snacks pouch", "travel-day", ["fly-cruise", "theme-park", "staycation"], ["kids", "long-travel-day"]),
  usefulExtra("kids:travel-game", "Travel game", "entertainment", ["fly-cruise", "staycation", "short-break"], ["kids", "long-travel-day"]),
  usefulExtra("kids:comfort-item", "Bedtime comfort item", "comfort", ["cruise", "fly-cruise", "staycation"], ["kids"]),
  usefulExtra("kids:cuddly-toy", "Favourite cuddly toy", "comfort", ["cruise", "fly-cruise", "staycation", "short-break"], ["kids"]),
  usefulExtra("kids:downloaded-videos", "Downloaded videos reminder", "entertainment", ["fly-cruise", "staycation", "short-break"], ["kids", "long-travel-day"]),
  usefulExtra("gadgets:spare-cable", "Spare charging cable", "electronics", ["cruise", "fly-cruise", "city-break", "theme-park"], ["gadgets"]),
  usefulExtra("gadgets:luggage-tracker", "Luggage tracker", "electronics", ["fly-cruise", "cruise", "city-break"], ["flight", "cruise-embarkation"]),
  usefulExtra("documents:passport-pouch", "Passport pouch", "documents", ["fly-cruise", "city-break", "beach-holiday", "cruise"], ["admin"]),
  usefulExtra("documents:printed-confirmations", "Printed confirmations", "documents", ["cruise", "fly-cruise", "city-break"], ["admin", "cruise-embarkation"]),
  usefulExtra("car:boot-organiser", "Car boot organiser", "misc", ["staycation", "short-break"], ["car"]),
  usefulExtra("dog:towel", "Dog towel", "pet", ["staycation", "short-break"], ["dog-friendly-stay"]),
  usefulExtra("dog:lead", "Dog lead", "pet", ["staycation", "short-break"], ["dog-friendly-stay"]),
  usefulExtra("dog:water-bowl", "Dog water bowl", "pet", ["staycation", "short-break"], ["dog-friendly-stay"]),
  usefulExtra("dog:food", "Dog food", "pet", ["staycation", "short-break"], ["dog-friendly-stay"]),
];

export const seededGadgetBundles: GadgetBundle[] = [
  gadgetBundle("iphone-travel-kit", "iPhone travel kit", ["cruise", "fly-cruise", "city-break", "theme-park"], ["phone", "travel-day"]),
  gadgetBundle("tablet-entertainment-kit", "Tablet entertainment kit", ["fly-cruise", "staycation", "short-break", "theme-park"], ["kids", "flight", "car"]),
  gadgetBundle("camera-kit", "Camera kit", ["cruise", "fly-cruise", "city-break", "theme-park"], ["photography"]),
  gadgetBundle("drone-kit", "Drone kit", ["staycation", "city-break"], ["photography", "outdoors"]),
  gadgetBundle("laptop-work-kit", "Laptop work kit", ["city-break", "family-visit", "short-break"], ["work"]),
  gadgetBundle("cruise-cabin-charging-kit", "Cruise cabin charging kit", ["cruise", "fly-cruise", "ex-uk-cruise"], ["cruise", "gadgets"]),
  gadgetBundle("theme-park-battery-kit", "Theme park battery kit", ["theme-park"], ["theme-park", "battery"]),
  gadgetBundle("travel-connectivity-kit", "Travel connectivity kit", ["cruise", "fly-cruise", "city-break", "staycation"], ["connectivity", "travel-day"]),
  gadgetBundle("headphones-audio-kit", "Headphones and audio kit", ["fly-cruise", "cruise", "city-break", "theme-park"], ["flight", "entertainment"]),
  gadgetBundle("family-charging-station", "Family charging station", ["cruise", "fly-cruise", "beach-holiday", "staycation"], ["family", "gadgets"]),
];

export const seededGadgetBundleItems: GadgetBundleItem[] = [
  gadgetBundleItem("iphone:phone", "iphone-travel-kit", "iPhone", true, "electronics", 1, ["device"], undefined, "pack"),
  gadgetBundleItem("iphone:charger", "iphone-travel-kit", "iPhone charger plug", true, "electronics", 1, ["charger"], "Needs iPhone charging cable.", "pack"),
  gadgetBundleItem("iphone:cable", "iphone-travel-kit", "iPhone charging cable", true, "electronics", 1, ["cable"], undefined, "pack"),
  gadgetBundleItem("iphone:power-bank", "iphone-travel-kit", "Power bank", false, "electronics", 1, ["battery"], "Needs charging cable.", "charge"),
  gadgetBundleItem("iphone:offline-maps", "iphone-travel-kit", "Offline maps", false, "electronics", 1, ["download"], undefined, "download"),
  gadgetBundleItem("iphone:case", "iphone-travel-kit", "Protective phone case", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("iphone:adapter", "iphone-travel-kit", "Travel plug adapter", false, "electronics", 1, ["adapter"]),
  gadgetBundleItem("iphone:tracker-check", "iphone-travel-kit", "Luggage tracker app check", false, "electronics", 1, ["check"], undefined, "check"),

  gadgetBundleItem("tablet:tablet", "tablet-entertainment-kit", "Tablet", true, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("tablet:case", "tablet-entertainment-kit", "Tablet case", true, "electronics", 1, ["accessory"]),
  gadgetBundleItem("tablet:headphones", "tablet-entertainment-kit", "Tablet headphones", true, "electronics", 1, ["audio"]),
  gadgetBundleItem("tablet:charging-cable", "tablet-entertainment-kit", "Tablet charging cable", true, "electronics", 1, ["cable"]),
  gadgetBundleItem("tablet:download-shows", "tablet-entertainment-kit", "Downloaded shows", false, "entertainment", 1, ["download"], undefined, "download"),
  gadgetBundleItem("tablet:download-games", "tablet-entertainment-kit", "Downloaded games", false, "entertainment", 1, ["download"], undefined, "download"),
  gadgetBundleItem("tablet:charger", "tablet-entertainment-kit", "Tablet charger plug", true, "electronics", 1, ["charger"]),

  gadgetBundleItem("camera:camera", "camera-kit", "Camera body", true, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("camera:battery", "camera-kit", "Camera battery", true, "electronics", 2, ["battery"], "Needs camera charger.", "charge"),
  gadgetBundleItem("camera:charger", "camera-kit", "Camera battery charger", true, "electronics", 1, ["charger"]),
  gadgetBundleItem("camera:memory-card", "camera-kit", "Memory cards", true, "electronics", 2, ["storage"]),
  gadgetBundleItem("camera:lens-cloth", "camera-kit", "Lens cloth", false, "electronics", 1, ["cleaning"]),
  gadgetBundleItem("camera:strap", "camera-kit", "Camera strap", true, "electronics", 1, ["accessory"]),
  gadgetBundleItem("camera:bag", "camera-kit", "Camera bag", false, "electronics", 1, ["bag"]),

  gadgetBundleItem("drone:drone", "drone-kit", "Drone", true, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("drone:batteries", "drone-kit", "Drone batteries", true, "electronics", 3, ["battery"], "Needs drone charger.", "charge"),
  gadgetBundleItem("drone:charger", "drone-kit", "Drone charger", true, "electronics", 1, ["charger"]),
  gadgetBundleItem("drone:propellers", "drone-kit", "Spare drone propellers", false, "electronics", 1, ["spare"]),
  gadgetBundleItem("drone:permit-check", "drone-kit", "Drone local rules check", true, "documents", 1, ["check"], undefined, "check"),
  gadgetBundleItem("drone:controller", "drone-kit", "Drone controller", true, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("drone:charging-hub", "drone-kit", "Drone charging hub", false, "electronics", 1, ["charger"]),
  gadgetBundleItem("drone:memory-card", "drone-kit", "Drone memory card", true, "electronics", 1, ["storage"]),
  gadgetBundleItem("drone:propeller-guards", "drone-kit", "Propeller guards", false, "electronics", 1, ["accessory"]),

  gadgetBundleItem("laptop:laptop", "laptop-work-kit", "Laptop", true, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("laptop:charger", "laptop-work-kit", "Laptop charger", true, "electronics", 1, ["charger"]),
  gadgetBundleItem("laptop:mouse", "laptop-work-kit", "Travel mouse", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("laptop:vpn", "laptop-work-kit", "Offline work files", false, "electronics", 1, ["download"], undefined, "download"),
  gadgetBundleItem("laptop:adapter", "laptop-work-kit", "Travel plug adapter", false, "electronics", 1, ["adapter"]),
  gadgetBundleItem("laptop:usb-c-hub", "laptop-work-kit", "USB-C hub", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("laptop:headset", "laptop-work-kit", "Work headset", false, "electronics", 1, ["audio"]),

  gadgetBundleItem("cruise:usb-hub", "cruise-cabin-charging-kit", "USB charging hub", true, "electronics", 1, ["charger"]),
  gadgetBundleItem("cruise:long-cable", "cruise-cabin-charging-kit", "Long charging cable", true, "electronics", 2, ["cable"]),
  gadgetBundleItem("cruise:plug-adapter", "cruise-cabin-charging-kit", "Travel plug adapter", true, "electronics", 1, ["adapter"]),
  gadgetBundleItem("cruise:cable-ties", "cruise-cabin-charging-kit", "Cable ties", false, "electronics", 1, ["organisation"]),
  gadgetBundleItem("cruise:usb-c-cables", "cruise-cabin-charging-kit", "USB-C cables", true, "electronics", 2, ["cable"]),
  gadgetBundleItem("cruise:watch-charger", "cruise-cabin-charging-kit", "Watch charger", false, "electronics", 1, ["charger"]),
  gadgetBundleItem("cruise:phone-cables", "cruise-cabin-charging-kit", "Phone charging cables", true, "electronics", 2, ["cable"]),

  gadgetBundleItem("theme-park:power-bank", "theme-park-battery-kit", "Large power bank", true, "electronics", 1, ["battery"], "Needs USB-C cable.", "charge"),
  gadgetBundleItem("theme-park:usb-c", "theme-park-battery-kit", "USB-C cable", true, "electronics", 1, ["cable"]),
  gadgetBundleItem("theme-park:phone-lanyard", "theme-park-battery-kit", "Phone lanyard", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("theme-park:short-cable", "theme-park-battery-kit", "Short charging cable", true, "electronics", 1, ["cable"]),
  gadgetBundleItem("theme-park:phone-grip", "theme-park-battery-kit", "Phone grip or stand", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("theme-park:waterproof-pouch", "theme-park-battery-kit", "Waterproof phone pouch", false, "electronics", 1, ["accessory"]),
  gadgetBundleItem("theme-park:tracker-check", "theme-park-battery-kit", "Tracker battery check", false, "electronics", 1, ["check"], undefined, "check"),

  gadgetBundleItem("connectivity:hotspot", "travel-connectivity-kit", "Mobile hotspot", false, "electronics", 1, ["device"], "Needs charging cable.", "charge"),
  gadgetBundleItem("connectivity:sim-tool", "travel-connectivity-kit", "SIM ejector tool", false, "electronics", 1, ["tool"]),
  gadgetBundleItem("connectivity:roaming-check", "travel-connectivity-kit", "Roaming plan check", true, "documents", 1, ["check"], undefined, "check"),
  gadgetBundleItem("connectivity:travel-router", "travel-connectivity-kit", "Travel router", false, "electronics", 1, ["device"], undefined, "charge"),
  gadgetBundleItem("connectivity:ethernet-cable", "travel-connectivity-kit", "Short network cable", false, "electronics", 1, ["cable"]),

  gadgetBundleItem("audio:headphones", "headphones-audio-kit", "Headphones", true, "electronics", 1, ["audio"]),
  gadgetBundleItem("audio:charging-cable", "headphones-audio-kit", "Headphones charging cable", true, "electronics", 1, ["cable"]),
  gadgetBundleItem("audio:bluetooth-adapter", "headphones-audio-kit", "Bluetooth audio adapter", false, "electronics", 1, ["audio"]),
  gadgetBundleItem("audio:splitter", "headphones-audio-kit", "Headphone splitter", false, "electronics", 1, ["audio"]),
  gadgetBundleItem("audio:downloaded-playlists", "headphones-audio-kit", "Downloaded playlists", false, "entertainment", 1, ["download"], undefined, "download"),

  gadgetBundleItem("family:charging-hub", "family-charging-station", "Multi-port USB charging hub", true, "electronics", 1, ["charger"]),
  gadgetBundleItem("family:travel-adapter", "family-charging-station", "Travel plug adapter", true, "electronics", 1, ["adapter"]),
  gadgetBundleItem("family:usb-c-cables", "family-charging-station", "USB-C charging cables", true, "electronics", 3, ["cable"]),
  gadgetBundleItem("family:phone-cables", "family-charging-station", "Phone charging cables", true, "electronics", 2, ["cable"]),
  gadgetBundleItem("family:watch-charger", "family-charging-station", "Watch charger", false, "electronics", 1, ["charger"]),
  gadgetBundleItem("family:cable-tidy", "family-charging-station", "Cable tidy", false, "electronics", 1, ["organisation"]),
];

export function createSeedSettings(now: string): AppSetting[] {
  return [
    {
      key: "appVersion",
      value: APP_VERSION,
      createdAt: now,
      updatedAt: now,
    },
    {
      key: "seedVersion",
      value: SEED_VERSION,
      createdAt: now,
      updatedAt: now,
    },
    {
      key: "seededAt",
      value: now,
      createdAt: now,
      updatedAt: now,
    },
    {
      key: "defaultCategories",
      value: seededCategories,
      createdAt: now,
      updatedAt: now,
    },
    {
      key: "defaultBagTypes",
      value: seededBagTypes,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function template(
  key: string,
  name: string,
  applicableTripTypes: Template["applicableTripTypes"],
  applicableContexts: string[],
): Template {
  return {
    id: `seed:template:${key}`,
    seedKey: `template:${key}`,
    seedVersion: SEED_VERSION,
    name,
    applicableTripTypes,
    applicableTravellers: ["adult", "child", "dog"],
    applicableContexts,
    active: true,
    description: `${name} starter suggestions.`,
    createdAt: "",
    updatedAt: "",
  };
}

function contextOptions(type: ContextOptionType, labels: string[]) {
  return labels.map<ContextOption>((label, sortOrder) => {
    const key = label
      .toLocaleLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "");
    return {
      id: `seed:context-option:${type}:${key}`,
      seedKey: `context-option:${type}:${key}`,
      seedVersion: SEED_VERSION,
      type,
      label,
      active: true,
      sortOrder,
      createdAt: "",
      updatedAt: "",
    };
  });
}

function templateItem(
  key: string,
  templateKey: string,
  name: string,
  ownerType: TemplateItem["ownerType"],
  category: string,
  priority: TemplateItem["priority"],
  conditionRules: TemplateConditionRule[] = [],
): TemplateItem {
  return {
    id: `seed:template-item:${key}`,
    seedKey: `template-item:${key}`,
    seedVersion: SEED_VERSION,
    templateId: `seed:template:${templateKey}`,
    name,
    ownerType,
    category,
    quantity: 1,
    priority,
    flags: [],
    conditionRules,
    createdAt: "",
    updatedAt: "",
  };
}

function usefulExtra(
  key: string,
  name: string,
  category: string,
  applicableTripTypes: UsefulExtra["applicableTripTypes"],
  applicableContexts: string[],
  forgottenBefore = false,
): UsefulExtra {
  return {
    id: `seed:useful-extra:${key}`,
    seedKey: `useful-extra:${key}`,
    seedVersion: SEED_VERSION,
    name,
    category,
    applicableTripTypes,
    applicableContexts,
    defaultPriority: forgottenBefore ? "important" : "useful",
    alwaysSuggest: forgottenBefore,
    neverSuggest: false,
    forgottenBefore,
    invaluableBefore: false,
    createdAt: "",
    updatedAt: "",
  };
}

function includesRule(
  field: TemplateConditionRule["field"],
  value: string,
): TemplateConditionRule {
  return {
    field,
    operator: "includes",
    value,
  };
}

function gadgetBundle(
  key: string,
  name: string,
  applicableTripTypes: TripType[],
  applicableContexts: string[],
): GadgetBundle {
  return {
    id: `seed:gadget-bundle:${key}`,
    seedKey: `gadget-bundle:${key}`,
    seedVersion: SEED_VERSION,
    name,
    applicableTripTypes,
    applicableContexts,
    notes: `${name} starter bundle.`,
    createdAt: "",
    updatedAt: "",
  };
}

function gadgetBundleItem(
  key: string,
  bundleKey: string,
  name: string,
  required: boolean,
  category: string,
  quantity: number,
  flags: string[],
  dependencyNotes?: string,
  preTripTaskType?: GadgetBundleItem["preTripTaskType"],
): GadgetBundleItem {
  return {
    id: `seed:gadget-bundle-item:${key}`,
    seedKey: `gadget-bundle-item:${key}`,
    seedVersion: SEED_VERSION,
    bundleId: `seed:gadget-bundle:${bundleKey}`,
    name,
    category,
    required,
    quantity,
    flags,
    dependencyNotes,
    preTripTaskType,
    createdAt: "",
    updatedAt: "",
  };
}
