import type { PackingAutocompleteEntry } from "./packing-autocomplete-types";
import { generatedPackingAutocompleteEntries } from "./packing-autocomplete-corpus.generated";

function entry(
  id: string,
  name: string,
  options: Omit<PackingAutocompleteEntry, "id" | "name" | "aliases"> & {
    aliases?: string[];
  } = {},
): PackingAutocompleteEntry {
  return { id, name, aliases: options.aliases ?? [], ...options };
}

export const packingAutocompleteCorpus: PackingAutocompleteEntry[] = [
  entry("documents:passports", "Passports", { aliases: ["passport"], categoryHint: "documents", ownerHint: "shared", priorityHint: "essential" }),
  entry("documents:boarding-passes", "Boarding passes", { aliases: ["flight boarding passes"], categoryHint: "documents", ownerHint: "shared", priorityHint: "essential" }),
  entry("documents:travel-insurance", "Travel insurance documents", { aliases: ["insurance", "policy"], categoryHint: "documents", ownerHint: "shared", priorityHint: "essential" }),
  entry("documents:hotel-confirmation", "Hotel booking confirmation", { aliases: ["hotel booking"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:cruise-boarding-pass", "Cruise boarding pass", { aliases: ["cruise documents"], categoryHint: "documents", ownerHint: "shared", priorityHint: "essential", tripTypeHints: ["cruise", "fly-cruise", "ex-uk-cruise"] }),
  entry("documents:cruise-luggage-labels", "Cruise luggage labels", { aliases: ["cruise luggage tags"], categoryHint: "documents", ownerHint: "shared", priorityHint: "essential", tripTypeHints: ["cruise", "fly-cruise", "ex-uk-cruise"] }),
  entry("documents:transfer-details", "Transfer details", { aliases: ["taxi transfer", "coach transfer"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:driving-licence", "Driving licence", { aliases: ["driver licence"], categoryHint: "documents", ownerHint: "adult", priorityHint: "essential" }),
  entry("documents:ghic", "GHIC card", { aliases: ["EHIC card", "health card"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:parking-confirmation", "Airport parking confirmation", { aliases: ["parking booking"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:car-hire-booking", "Car hire booking", { aliases: ["rental car booking"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:travel-money", "Travel money", { aliases: ["cash", "foreign currency"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:bank-cards", "Bank cards", { aliases: ["credit cards", "debit cards"], categoryHint: "documents", ownerHint: "adult", priorityHint: "essential" }),
  entry("documents:emergency-contacts", "Emergency contacts", { aliases: ["emergency numbers"], categoryHint: "documents", ownerHint: "shared", priorityHint: "important" }),
  entry("documents:pet-insurance", "Dog insurance details", { aliases: ["pet insurance"], categoryHint: "documents", ownerHint: "dog", priorityHint: "important" }),

  entry("clothing:t-shirts", "T-shirts", { aliases: ["tees"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:shorts", "Shorts", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:jeans", "Jeans", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:underwear", "Underwear", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("clothing:socks", "Socks", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("clothing:pyjamas", "Pyjamas", { aliases: ["pjs"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:hoodie", "Hoodie", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:jumper", "Jumper", { aliases: ["sweater"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:cardigan", "Cardigan", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:waterproof-jacket", "Waterproof jacket", { aliases: ["rain jacket"], categoryHint: "weather", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:coat", "Coat", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:swim-shorts", "Swim shorts", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important", tripTypeHints: ["beach-holiday", "cruise", "fly-cruise"] }),
  entry("clothing:swimsuit", "Swimsuit", { aliases: ["swimming costume"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:bikini", "Bikini", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:rash-vest", "Rash vest", { aliases: ["rashie"], categoryHint: "clothing", ownerHint: "child", priorityHint: "important" }),
  entry("clothing:formal-shirt", "Formal shirt", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important", tripTypeHints: ["cruise", "fly-cruise"] }),
  entry("clothing:evening-dress", "Evening dress", { categoryHint: "clothing", ownerHint: "beck", priorityHint: "important", tripTypeHints: ["cruise", "fly-cruise"] }),
  entry("clothing:smart-trousers", "Smart trousers", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:smart-shoes", "Smart shoes", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:sandals", "Sandals", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("clothing:flip-flops", "Flip flops", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "useful" }),
  entry("clothing:trainers", "Trainers", { aliases: ["sneakers"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),

  entry("toiletries:toothbrush", "Toothbrush", { categoryHint: "toiletries", ownerHint: "adult", priorityHint: "essential" }),
  entry("toiletries:toothpaste", "Toothpaste", { categoryHint: "toiletries", ownerHint: "shared", priorityHint: "essential" }),
  entry("toiletries:deodorant", "Deodorant", { categoryHint: "toiletries", ownerHint: "adult", priorityHint: "essential" }),
  entry("toiletries:shampoo", "Shampoo", { categoryHint: "toiletries", ownerHint: "shared", priorityHint: "important" }),
  entry("toiletries:conditioner", "Conditioner", { categoryHint: "toiletries", ownerHint: "shared", priorityHint: "useful" }),
  entry("toiletries:shower-gel", "Shower gel", { categoryHint: "toiletries", ownerHint: "shared", priorityHint: "important" }),
  entry("toiletries:hairbrush", "Hairbrush", { categoryHint: "toiletries", ownerHint: "adult", priorityHint: "important" }),
  entry("toiletries:make-up-bag", "Make-up bag", { aliases: ["makeup"], categoryHint: "toiletries", ownerHint: "beck", priorityHint: "important" }),
  entry("toiletries:straighteners", "Hair straighteners", { categoryHint: "toiletries", ownerHint: "beck", priorityHint: "useful" }),
  entry("toiletries:razor", "Razor", { categoryHint: "toiletries", ownerHint: "adult", priorityHint: "important" }),
  entry("health:sun-cream", "Sun cream", { aliases: ["sunscreen", "spf"], categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("health:after-sun", "After sun", { categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("health:lip-balm", "Lip balm", { categoryHint: "health", ownerHint: "shared", priorityHint: "useful" }),
  entry("health:plasters", "Plasters", { aliases: ["band aids"], categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("health:calpol", "Calpol", { aliases: ["child medicine"], categoryHint: "health", ownerHint: "seb", priorityHint: "essential" }),
  entry("health:painkillers", "Painkillers", { categoryHint: "health", ownerHint: "shared", priorityHint: "essential" }),
  entry("health:antihistamines", "Antihistamines", { categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("health:travel-sickness-tablets", "Travel sickness tablets", { categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("health:prescription-medication", "Prescription medication", { aliases: ["medicines"], categoryHint: "health", ownerHint: "adult", priorityHint: "essential" }),
  entry("health:first-aid-kit", "First aid kit", { categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),

  entry("electronics:phone-charger", "Phone charger", { aliases: ["charger"], categoryHint: "electronics", ownerHint: "adult", priorityHint: "essential", statusHint: "to-charge" }),
  entry("electronics:usb-c-cable", "USB-C cable", { aliases: ["usb c cable"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "important" }),
  entry("electronics:lightning-cable", "Lightning cable", { aliases: ["iphone cable"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "important" }),
  entry("electronics:plug-adapter", "Plug adapter", { aliases: ["travel adapter"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "important" }),
  entry("electronics:power-bank", "Power bank", { aliases: ["battery pack", "power banks"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("electronics:charging-hub", "Charging hub", { aliases: ["usb hub"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful" }),
  entry("electronics:usb-plug", "USB plug", { aliases: ["usb charger plug"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "important" }),
  entry("electronics:laptop-charger", "Laptop charger", { categoryHint: "electronics", ownerHint: "adult", priorityHint: "essential", statusHint: "to-charge" }),
  entry("electronics:tablet-charger", "iPad/tablet charger", { aliases: ["ipad charger", "tablet charger"], categoryHint: "electronics", ownerHint: "seb", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("electronics:headphones", "Headphones", { categoryHint: "electronics", ownerHint: "adult", priorityHint: "important", statusHint: "to-charge" }),
  entry("electronics:airpods", "AirPods", { aliases: ["earbuds"], categoryHint: "electronics", ownerHint: "adult", priorityHint: "important", statusHint: "to-charge" }),
  entry("electronics:extension-lead", "Extension lead", { categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful" }),
  entry("electronics:cable-organiser", "Cable organiser", { aliases: ["cable tidy"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful" }),
  entry("electronics:airtags", "AirTags", { aliases: ["air tags", "luggage trackers"], categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful", statusHint: "to-charge", familySpecific: true }),
  entry("electronics:phone-stand", "Phone stand", { categoryHint: "electronics", ownerHint: "shared", priorityHint: "nice-to-have", familySpecific: true }),

  entry("photography:camera", "Camera", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge" }),
  entry("photography:camera-battery", "Camera battery", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge" }),
  entry("photography:camera-charger", "Camera charger", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge" }),
  entry("photography:camera-memory-cards", "Camera memory cards", { aliases: ["memory cards", "sd cards"], categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", familySpecific: true }),
  entry("photography:spare-sd-card", "Spare SD card", { aliases: ["sd card"], categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful" }),
  entry("photography:lens-cloth", "Lens cloth", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful" }),
  entry("photography:camera-strap", "Camera strap", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful" }),
  entry("photography:drone", "Drone", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("photography:drone-controller", "Drone controller", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("photography:drone-batteries", "Drone batteries", { aliases: ["drone battery"], categoryHint: "electronics", ownerHint: "phil", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("photography:drone-charging-hub", "Drone charging hub", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful", statusHint: "to-charge" }),
  entry("photography:drone-memory-card", "Drone memory card", { aliases: ["drone sd card"], categoryHint: "electronics", ownerHint: "phil", priorityHint: "important" }),
  entry("photography:action-camera", "Action camera", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful", statusHint: "to-charge" }),
  entry("photography:selfie-stick", "Selfie stick", { categoryHint: "electronics", ownerHint: "shared", priorityHint: "nice-to-have" }),
  entry("photography:mini-tripod", "Mini tripod", { categoryHint: "electronics", ownerHint: "phil", priorityHint: "useful" }),
  entry("photography:phone-tripod", "Phone tripod", { categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful" }),
  entry("photography:osmo-pocket-accessories", "Osmo Pocket accessories", { aliases: ["osmo pocket"], categoryHint: "electronics", ownerHint: "phil", priorityHint: "nice-to-have" }),

  entry("child:toniebox", "Toniebox", { aliases: ["tonie box"], categoryHint: "entertainment", ownerHint: "seb", priorityHint: "important", statusHint: "to-charge", familySpecific: true }),
  entry("child:tonies", "Tonies", { aliases: ["tonie figures"], categoryHint: "entertainment", ownerHint: "seb", priorityHint: "important", familySpecific: true }),
  entry("child:jellycat", "Jellycat", { aliases: ["cuddly toy"], categoryHint: "comfort", ownerHint: "seb", priorityHint: "important", familySpecific: true }),
  entry("child:tablet", "Tablet", { aliases: ["ipad"], categoryHint: "electronics", ownerHint: "seb", priorityHint: "important", statusHint: "to-charge" }),
  entry("child:tablet-headphones", "Tablet headphones", { aliases: ["child headphones"], categoryHint: "electronics", ownerHint: "seb", priorityHint: "important", familySpecific: true }),
  entry("child:downloaded-films", "Downloaded films", { aliases: ["downloaded movies"], categoryHint: "entertainment", ownerHint: "seb", priorityHint: "useful", statusHint: "to-download", familySpecific: true }),
  entry("child:downloaded-games", "Downloaded games", { categoryHint: "entertainment", ownerHint: "seb", priorityHint: "useful", statusHint: "to-download" }),
  entry("child:activity-book", "Activity book", { categoryHint: "entertainment", ownerHint: "seb", priorityHint: "useful" }),
  entry("child:colouring-pencils", "Colouring pencils", { categoryHint: "entertainment", ownerHint: "seb", priorityHint: "useful" }),
  entry("child:notebook", "Small notebook", { categoryHint: "entertainment", ownerHint: "seb", priorityHint: "nice-to-have" }),
  entry("child:travel-game", "Travel game", { categoryHint: "entertainment", ownerHint: "seb", priorityHint: "useful" }),
  entry("child:swim-goggles", "Swim goggles", { aliases: ["goggles"], categoryHint: "misc", ownerHint: "seb", priorityHint: "useful", familySpecific: true }),
  entry("child:cap", "Cap", { aliases: ["baseball cap"], categoryHint: "clothing", ownerHint: "child", priorityHint: "important" }),
  entry("child:bedtime-comfort", "Seb bedtime comfort item", { aliases: ["bedtime comfort item", "comforter"], categoryHint: "comfort", ownerHint: "seb", priorityHint: "important", familySpecific: true }),
  entry("child:snacks", "Travel day snacks", { aliases: ["snacks"], categoryHint: "travel-day", ownerHint: "shared", priorityHint: "useful", familySpecific: true }),
  entry("child:water-bottle", "Water bottle", { aliases: ["refillable bottle"], categoryHint: "travel-day", ownerHint: "child", priorityHint: "important" }),

  entry("cruise:lanyards", "Cruise lanyards", { aliases: ["lanyards", "cruise card lanyards"], categoryHint: "cruise-extras", ownerHint: "shared", priorityHint: "useful", tripTypeHints: ["cruise", "fly-cruise", "ex-uk-cruise"], familySpecific: true }),
  entry("cruise:magnetic-hooks", "Magnetic hooks", { aliases: ["magnetic cabin hooks"], categoryHint: "cruise-extras", ownerHint: "shared", priorityHint: "useful", tripTypeHints: ["cruise", "fly-cruise", "ex-uk-cruise"], familySpecific: true }),
  entry("cruise:cabin-night-light", "Cabin night light", { aliases: ["night light"], categoryHint: "cruise-extras", ownerHint: "shared", priorityHint: "useful" }),
  entry("cruise:over-door-organiser", "Over-door organiser", { categoryHint: "cruise-extras", ownerHint: "shared", priorityHint: "nice-to-have" }),
  entry("cruise:laundry-bag", "Laundry bag", { categoryHint: "laundry", ownerHint: "shared", priorityHint: "useful" }),
  entry("cruise:washing-line", "Travel washing line", { categoryHint: "laundry", ownerHint: "shared", priorityHint: "useful" }),
  entry("cruise:embarkation-bag", "Cruise embarkation bag", { categoryHint: "travel-day", ownerHint: "shared", priorityHint: "important" }),
  entry("cruise:formal-night-outfit", "Formal night outfit", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("cruise:sea-sickness-bands", "Sea sickness bands", { categoryHint: "health", ownerHint: "shared", priorityHint: "useful" }),
  entry("cruise:excursion-bag", "Excursion bag", { categoryHint: "travel-day", ownerHint: "shared", priorityHint: "important" }),
  entry("cruise:door-magnets", "Door magnets", { categoryHint: "cruise-extras", ownerHint: "shared", priorityHint: "nice-to-have" }),

  entry("beach:beach-bag", "Beach bag", { categoryHint: "travel-day", ownerHint: "shared", priorityHint: "important" }),
  entry("beach:wet-bag", "Wet bag", { categoryHint: "travel-day", ownerHint: "shared", priorityHint: "useful" }),
  entry("beach:towel-clips", "Towel clips", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("beach:sun-hat", "Sun hat", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("beach:sunglasses", "Sunglasses", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("beach:pool-shoes", "Pool shoes", { aliases: ["beach shoes"], categoryHint: "clothing", ownerHint: "child", priorityHint: "useful" }),
  entry("beach:snorkel", "Snorkel", { categoryHint: "misc", ownerHint: "child", priorityHint: "nice-to-have" }),
  entry("beach:beach-toys", "Beach toys", { categoryHint: "entertainment", ownerHint: "child", priorityHint: "useful" }),
  entry("beach:inflatables", "Inflatables", { categoryHint: "misc", ownerHint: "shared", priorityHint: "nice-to-have" }),

  entry("theme-park:ponchos", "Disney/theme park ponchos", { aliases: ["ponchos", "rain ponchos"], categoryHint: "weather", ownerHint: "shared", priorityHint: "useful", tripTypeHints: ["theme-park"], familySpecific: true }),
  entry("theme-park:comfortable-shoes", "Comfortable shoes", { aliases: ["walking shoes"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("theme-park:cooling-towel", "Cooling towel", { categoryHint: "comfort", ownerHint: "shared", priorityHint: "useful" }),
  entry("theme-park:portable-fan", "Portable fan", { categoryHint: "comfort", ownerHint: "shared", priorityHint: "useful", statusHint: "to-charge" }),
  entry("theme-park:park-bag", "Park bag", { aliases: ["theme park bag"], categoryHint: "travel-day", ownerHint: "shared", priorityHint: "essential" }),
  entry("theme-park:autograph-book", "Autograph book", { categoryHint: "entertainment", ownerHint: "child", priorityHint: "nice-to-have" }),
  entry("theme-park:hand-sanitiser", "Hand sanitiser", { aliases: ["sanitizer"], categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("theme-park:blister-plasters", "Blister plasters", { categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),

  entry("cold:thermals", "Thermals", { aliases: ["base layers"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential", tripTypeHints: ["cold-weather"] }),
  entry("cold:thermal-socks", "Thermal socks", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("cold:gloves", "Gloves", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("cold:hats", "Warm hats", { aliases: ["winter hat"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("cold:scarves", "Scarves", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("cold:snow-boots", "Snow boots", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("cold:waterproof-trousers", "Waterproof trousers", { categoryHint: "weather", ownerHint: "adult", priorityHint: "important" }),
  entry("cold:winter-coat", "Winter coat", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "essential" }),
  entry("cold:hand-warmers", "Hand warmers", { categoryHint: "comfort", ownerHint: "shared", priorityHint: "useful" }),
  entry("cold:moisturiser", "Moisturiser", { categoryHint: "toiletries", ownerHint: "shared", priorityHint: "useful" }),
  entry("cold:neck-warmer", "Neck warmer", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),

  entry("staycation:car-snacks", "Car snacks", { categoryHint: "travel-day", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:car-charger", "Car charger", { categoryHint: "electronics", ownerHint: "shared", priorityHint: "useful", statusHint: "to-charge" }),
  entry("staycation:car-blanket", "Car blanket", { categoryHint: "comfort", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:wellies", "Wellies", { aliases: ["wellington boots"], categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("staycation:walking-boots", "Walking boots", { categoryHint: "clothing", ownerHint: "adult", priorityHint: "important" }),
  entry("staycation:board-games", "Board games", { categoryHint: "entertainment", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:food-basics", "Food basics", { categoryHint: "misc", ownerHint: "shared", priorityHint: "important" }),
  entry("staycation:tea-bags", "Tea bags", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:washing-up-liquid", "Washing-up liquid", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:bin-bags", "Bin bags", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:kitchen-roll", "Kitchen roll", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("staycation:towels", "Towels", { categoryHint: "misc", ownerHint: "shared", priorityHint: "important" }),
  entry("staycation:bedding", "Bedding", { categoryHint: "comfort", ownerHint: "shared", priorityHint: "important" }),

  entry("dog:lead", "Albert lead", { aliases: ["dog lead"], categoryHint: "pet", ownerHint: "albert", priorityHint: "essential", familySpecific: true }),
  entry("dog:spare-lead", "Spare dog lead", { categoryHint: "pet", ownerHint: "albert", priorityHint: "important" }),
  entry("dog:towel", "Albert towel", { aliases: ["dog towel"], categoryHint: "pet", ownerHint: "albert", priorityHint: "important", familySpecific: true }),
  entry("dog:bowls", "Albert bowls", { aliases: ["dog bowls"], categoryHint: "pet", ownerHint: "albert", priorityHint: "essential", familySpecific: true }),
  entry("dog:food", "Dog food", { categoryHint: "pet", ownerHint: "albert", priorityHint: "essential" }),
  entry("dog:treats", "Dog treats", { categoryHint: "pet", ownerHint: "albert", priorityHint: "important" }),
  entry("dog:poo-bags", "Poo bags", { aliases: ["dog poo bags"], categoryHint: "pet", ownerHint: "albert", priorityHint: "essential" }),
  entry("dog:bed", "Albert dog bed", { aliases: ["dog bed"], categoryHint: "pet", ownerHint: "albert", priorityHint: "important", familySpecific: true }),
  entry("dog:blanket", "Dog blanket", { categoryHint: "pet", ownerHint: "albert", priorityHint: "important" }),
  entry("dog:drying-robe", "Dog drying robe", { categoryHint: "pet", ownerHint: "albert", priorityHint: "useful" }),
  entry("dog:medication", "Dog medication", { categoryHint: "pet", ownerHint: "albert", priorityHint: "essential" }),
  entry("dog:tick-remover", "Tick remover", { categoryHint: "pet", ownerHint: "albert", priorityHint: "important" }),
  entry("dog:car-harness", "Dog car harness", { categoryHint: "pet", ownerHint: "albert", priorityHint: "essential" }),
  entry("dog:water-bottle", "Dog water bottle", { categoryHint: "pet", ownerHint: "albert", priorityHint: "important" }),

  entry("extras:ziplock-bags", "Ziplock bags", { aliases: ["ziploc bags"], categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("extras:collapsible-bag", "Collapsible bag", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("extras:shopping-bag", "Reusable shopping bag", { categoryHint: "misc", ownerHint: "shared", priorityHint: "useful" }),
  entry("extras:eye-mask", "Eye mask", { categoryHint: "comfort", ownerHint: "adult", priorityHint: "useful" }),
  entry("extras:ear-plugs", "Ear plugs", { categoryHint: "comfort", ownerHint: "adult", priorityHint: "useful" }),
  entry("extras:travel-pillow", "Travel pillow", { categoryHint: "comfort", ownerHint: "adult", priorityHint: "useful" }),
  entry("extras:anti-bac-wipes", "Anti-bac wipes", { aliases: ["antibacterial wipes"], categoryHint: "health", ownerHint: "shared", priorityHint: "important" }),
  entry("extras:tissues", "Tissues", { categoryHint: "health", ownerHint: "shared", priorityHint: "useful" }),
  entry("extras:spare-sunglasses", "Spare sunglasses", { categoryHint: "clothing", ownerHint: "shared", priorityHint: "useful" }),
  ...generatedPackingAutocompleteEntries,
];
